import { Colors, Typography, Layout } from "../../theme.slint";
import { ActionButton, ModalOverlay } from "../common.slint";

export component AddConnectionDialog inherits ModalOverlay {
    callback no-clicked;
    callback yes-clicked;

    VerticalLayout {
        padding: Layout.padding-2xl;
        spacing: Layout.spacing-2xl;
        alignment: start;

        Text {
            text: @tr("Warning");
            color: Colors.yellow;
            font-size: Typography.size-xl;
            font-weight: 700;
        }

        Text {
            text: @tr("Connection test was not successful. Add anyway?");
            color: Colors.text;
            font-size: Typography.size-lg;
            wrap: word-wrap;
        }

        HorizontalLayout {
            spacing: Layout.spacing-lg;
            alignment: end;
            ActionButton {
                width: 80px;
                text: @tr("No");
                clicked => { root.no-clicked(); }
            }
            ActionButton {
                width: 80px;
                text: @tr("Yes");
                bg: Colors.red;
                fg: Colors.base;
                clicked => { root.yes-clicked(); }
            }
        }
    }
}
