use anyhow::Result;
use clap::{Parser, Subcommand};
use colored::Colorize;
use std::process::{Command, Stdio};
use std::time::Instant;

#[derive(Parser)]
#[command(name = "x")]
#[command(about = "Development automation for wellfeather")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Run pre-commit checks (fmt-check, clippy, test)
    PreCommit,
    /// Install git pre-commit hook
    InstallHooks,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::PreCommit => run_pre_commit(),
        Commands::InstallHooks => install_hooks(),
    }
}

fn run_pre_commit() -> Result<()> {
    println!("{}", "=== Pre-commit Checks ===".bold().blue());

    let start = Instant::now();

    run_step("Format Check", || {
        execute_command(
            Command::new("cargo")
                .arg("fmt")
                .arg("--all")
                .arg("--")
                .arg("--check"),
        )
    })?;

    run_step("Clippy", || {
        execute_command(
            Command::new("cargo")
                .arg("clippy")
                .arg("--workspace")
                .arg("--all-targets")
                .arg("--")
                .arg("-D")
                .arg("warnings"),
        )
    })?;

    run_step("Test", || {
        execute_command(Command::new("cargo").arg("test").arg("--workspace"))
    })?;

    let elapsed = start.elapsed();
    println!(
        "\n{} {}",
        "✓ Pre-commit checks passed in".green().bold(),
        format!("{:.2}s", elapsed.as_secs_f64()).bold()
    );

    Ok(())
}

fn install_hooks() -> Result<()> {
    use std::fs;

    println!("{}", "Installing git hooks...".bold());

    let hook_content = r#"#!/bin/sh
# Auto-generated by cargo x install-hooks
set -e

echo "Running pre-commit checks..."
cargo x pre-commit
"#;

    let hook_path = ".git/hooks/pre-commit";
    fs::write(hook_path, hook_content)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(hook_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(hook_path, perms)?;
    }

    println!("{}", "✓ Git hooks installed".green());
    println!("  Pre-commit hook will run: fmt-check, clippy, test");

    Ok(())
}

fn run_step<F>(name: &str, task: F) -> Result<()>
where
    F: FnOnce() -> Result<()>,
{
    print!("{} {} ... ", "→".blue(), name);

    let start = Instant::now();

    match task() {
        Ok(_) => {
            let elapsed = start.elapsed();
            println!("{} ({:.2}s)", "✓".green().bold(), elapsed.as_secs_f64());
            Ok(())
        }
        Err(e) => {
            println!("{}", "✗".red().bold());
            Err(e)
        }
    }
}

fn execute_command(cmd: &mut Command) -> Result<()> {
    let status = cmd
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .status()?;

    if !status.success() {
        anyhow::bail!("Command failed with exit code: {}", status);
    }

    Ok(())
}
